services:
  cfp-session-eval-council-proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: cfp-session-eval-council-proxy
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    restart: unless-stopped

  cfp-session-eval-council-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cfp-session-eval-council-app:latest
    container_name: cfp-session-eval-council-app
    ports:
      - "8080:80"
    depends_on:
      - cfp-session-eval-council-proxy
    restart: unless-stopped
